name: Jinying's Blog
title: Jinying & My Love
description: "🌌 2026 七夕专属浪漫限定 · Love you to the moon and back"
baseurl: ""
url: "https://tujinying.me"
github_username: tujy859
permalink: /:year/:month/:day/:title/
future: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - "node_modules"
  - "vendor/bundle"
  - "Gemfile"
  - "Gemfile.lock"

author:
  name: "Jinying Tu"

social:
  github: "https://github.com/tujy859"
