name: My Blog
title: My Blog
description: "My blogs for learning and recording"
baseurl: ""
url: "https://tujy859.github.io"
github_username: tujy859
permalink: /:year/:month/:day/:title/
future: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - "node_modules"
  - "vendor/bundle"
  - "Gemfile"
  - "Gemfile.lock"

author:
  name: "Jinying Tu"

social:
  github: "https://github.com/tujy859"
